In [18]:
import numpy as np
import torch

from lib.Tensor import Tensor

In [19]:
data = np.random.randn(2, 3) * 3

a = Tensor(data, requires_grad=True)
a = a.clip(2, 8)
a.sum().backward()

a_pt = torch.tensor(data, requires_grad=True)
a_pt = a_pt.clip(2, 8)
a_pt.sum().backward()

In [20]:
print(a.grad)
print(a_pt.grad)

[[1. 1. 1.]
 [1. 1. 1.]]
None


/var/folders/6t/m1cj5jqd1cx9xq5bxs_h3g200000gn/T/ipykernel_83925/954677892.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(a_pt.grad)


In [26]:
x_data = np.random.rand(10, 5)
y_data = np.random.randint(0, 5, size=(10,1))

x = Tensor(x_data, requires_grad=True)
y = Tensor(y_data, requires_grad=True)

In [27]:
epsilon = 1e-12
x.clip(epsilon, 1 - epsilon)

Tensor([[0.32585671 0.2932958  0.64263918 0.59614046 0.61774382]
 [0.04047177 0.64687904 0.49243823 0.14357895 0.26889615]
 [0.42671793 0.62874981 0.37634977 0.42806211 0.14612539]
 [0.06158747 0.27286321 0.92372379 0.09474398 0.38038477]
 [0.8138277  0.28546407 0.69025764 0.14253811 0.9759206 ]
 [0.21995289 0.65508706 0.76853784 0.35089782 0.6958695 ]
 [0.52867313 0.70560274 0.13798282 0.76022937 0.58267696]
 [0.85133483 0.63501001 0.95235131 0.85611409 0.47802595]
 [0.35250522 0.64806383 0.50537053 0.31774278 0.06645085]
 [0.61196008 0.81090009 0.29843122 0.43424096 0.15658913]], requires_grad=True)

In [28]:
y * x.log()

Tensor([[ -3.36389262  -3.67972091  -1.3265156   -1.55183688  -1.44504433]
 [ -3.20715059  -0.43559595  -0.70838624  -1.94087023  -1.31343005]
 [ -1.70326414  -0.92804371  -1.95447267  -1.69697396  -3.84658039]
 [-11.14918756  -5.19513871  -0.31736871  -9.42630788  -3.86628792]
 [ -0.61801982  -3.76091734  -1.11207108  -5.84443755  -0.07312215]
 [ -3.02868381  -0.84597426  -0.52653097  -2.09452043  -0.72518628]
 [ -0.63738494  -0.3487029   -1.9806261   -0.27413509  -0.54012235]
 [ -0.48284931  -1.36234353  -0.14646388  -0.46605488  -2.21427081]
 [ -4.17075941  -1.73506437  -2.72985358  -4.58605242 -10.8451709 ]
 [ -1.96435293  -0.83844169  -4.83686321  -3.33662272  -7.41651963]], requires_grad=True)

In [ ]:
from lin.NN import Loss

class CrossEntropyLoss(Loss):
    def forward(self, x: Tensor, y: Tensor) -> Tensor:
        self.input = (x, y)
        epsilon = 1e-12
        x.clip(epsilon, 1. - epsilon) # clip to avoid log(0)
        ce = - (y * x.log() + (1. - y) * (1. - x).log()).mean() # cross entropy
        return ce