In [6]:
import numpy as np

from lib.Tensor import Tensor, no_grad
from lib.NN import ReLU, Dense, Module, CrossEntropyLoss
from lib.Optimizers import SGD

from lib.data_utils import get_mnist

In [7]:
path = "/Users/beneverman/Documents/Coding/bens-mini-dl/data"
x_train, y_train, x_valid, y_valid = get_mnist(path)

In [8]:
print(x_train.shape) # (n images, n pixels)
print(y_train.shape) # (class labels,)


print(x_valid.shape) # (n images, n pixels)
print(y_valid.shape) # (class labels,)

input_dim = x_train.shape[1] # number of features (pixels)
output_dim = len(set(y_train)) # all unique class labels

(50000, 784)
(50000,)
(10000, 784)
(10000,)


In [9]:
x_train_tensor = Tensor(x_train, requires_grad=True)
y_train_tensor = Tensor(y_train, requires_grad=True)
x_val_tensor = Tensor(x_valid, requires_grad=True)
y_val_tensor = Tensor(y_valid, requires_grad=True)

In [10]:
class MLP(Module):
    def __init__(self, input_dim: int, output_dim: int):
        super().__init__()
        self.fc1 = Dense(input_dim, 64)
        self.relu1 = ReLU()
        self.fc2 = Dense(64, output_dim)

    def forward(self, x):   
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        return x
    
model = MLP(input_dim, output_dim)

IndexError: tuple index out of range

In [ ]:
criterion = CrossEntropyLoss()
optimizer = SGD(model.parameters(), lr=0.001)

In [ ]:
x_train_tensor[0:64]

Tensor([[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], requires_grad=True)

In [ ]:
EPOCHS = 100
batch_size = 64

for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0

    for i in range(0, len(x_train_tensor), batch_size):
        x_batch = x_train_tensor[i:i+batch_size] # TODO add data shuffling
        y_batch = y_train_tensor[i:i+batch_size] # TODO add data shuffling

        optimizer.zero_grad()

        output = model(x_batch)

        loss = criterion(output, y_batch)

        loss.backward()
        optimizer.step()

        train_loss += loss.data * x_batch.shape[0]

    model.eval()
    val_loss = 0.0

    with no_grad():
        for i in range(0, len(x_val_tensor), batch_size):
            x_batch = x_val_tensor[i:i+batch_size]
            y_batch = y_val_tensor[i:i+batch_size]

            output = model(x_batch)

            loss = criterion(output, y_batch)

            val_loss += loss.data * x_batch.shape[0]

    train_loss = train_loss / len(x_train_tensor)
    val_loss = val_loss / len(x_val_tensor)

    if epoch % 10 == 0:
        print(f"Epoch: {epoch + 1} | Train Loss: {train_loss:0.4f} | Val Loss: {val_loss:0.4f}")

ValueError: operands could not be broadcast together with shapes (64,) (64,10) 