In [1]:
import numpy as np
import torch

from lib.Tensor import Tensor

In [2]:
data1, data2 = np.random.randn(2, 3), np.random.randn(2, 3) # random data

# ! Custom Tensor class
t1 = Tensor(data1, requires_grad=True) # init
t2 = Tensor(data2, requires_grad=True) # init
pt1 = torch.Tensor(data1).double().requires_grad_(True) # pytorch
pt2 = torch.Tensor(data2).double().requires_grad_(True) # pytorch

def ops(a, b):
    c = a * b
    return c.sum()

def ops_2(a, b):
    # ! THIS FAILS
    c = a + b # add, radd
    d = c - b # sub, rsub
    e = c * 2 # mul scalar
    x = d * e # mul tensor (elementwise)
    return x.sum()

In [3]:
result1 = ops_2(t1, t2)
result2 = ops_2(pt1, pt2)

In [4]:
result1.backward()
result2.backward()

In [5]:
def check_tol(t1, t2, pt1, pt2):
    tols = [1e-10, 1e-8, 1e-6, 1e-4, 1e-2]
    for tol in tols:
        print(f"tol: {tol}")
        print(np.allclose(t1.grad, pt1.grad.numpy(), atol=tol))
        print(np.allclose(t2.grad, pt2.grad.numpy(), atol=tol))

In [6]:
print(f"t1 grad {t1.grad}")
print(f"pt1 grad {pt1.grad.numpy()}")
print(f"t2 grad {t2.grad}") 
print(f"pt2 grad {pt2.grad.numpy()}")

t1 grad [[11.22844024 -0.59016627  5.79351045]
 [ 3.7700739   3.36832697 -4.32833888]]
pt1 grad [[ 7.19164854 -0.12214404  4.16472638]
 [ 2.18861103  1.28201962 -2.95289603]]
t2 grad [[ 7.1916486  -0.12214406  4.16472655]
 [ 2.18861101  1.28201964 -2.952896  ]]
pt2 grad [[ 3.15485692  0.34587815  2.53594255]
 [ 0.60714811 -0.80428767 -1.57745314]]


In [47]:
check_tol(t1, t2, pt1, pt2)

tol: 1e-10
True
True
tol: 1e-08
True
True
tol: 1e-06
True
True
tol: 0.0001
True
True
tol: 0.01
True
True


In [53]:
result3 = ops_2(t1, t2)
result4 = ops_2(pt1, pt2)

result3.backward()
result4.backward()

print(f"t1 grad {t1.grad}")
print(f"pt1 grad {pt1.grad.numpy()}")

print(f"t2 grad {t2.grad}")
print(f"pt2 grad {pt2.grad.numpy()}")

t1 grad [[ 0.25706986 -2.53289069 -8.23273654]
 [ 0.53637653 -4.95895261  2.1283796 ]]
pt1 grad [[-0.81876063 -1.04067016 -5.24569333]
 [ 0.18049803 -3.24273695  1.55202657]]
t2 grad [[-0.81876055 -1.04067013 -5.24569314]
 [ 0.18049802 -3.24273697  1.55202658]]
pt2 grad [[-1.89459097  0.45155042 -2.25864983]
 [-0.17538048 -1.52652133  0.97567356]]
