In [3]:
from lib.Tensor import Tensor
import numpy as np

In [6]:
data = np.random.rand(2, 3) * 10 # between 0 and 10
print(data)

[[9.64835952 3.78846869 3.40990562]
 [1.35263257 5.42079619 5.37357574]]


In [7]:
a = Tensor(data, requires_grad=True)

In [10]:
a = a.clip(2, 8)

In [11]:
a.data

array([[8.        , 3.78846869, 3.40990562],
       [2.        , 5.42079619, 5.37357574]])